pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - 'label!=do-not-merge :x:'
      - '#approved-reviews-by=@konojunya'
      - 'status-success=ci/circleci: setup'
      - 'status-success=ci/circleci: run_build'
      - 'status-success=ci/circleci: run_lint'
      - 'status-success=ci/circleci: run_test'
    actions:
      delete_head_branch: {}
      merge:
        method: merge
  
  # Labels
  - name: Auto add wip label
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ['in-progress :white_check_mark:']
  
  - name: Auto remove wip label
    conditions:
      - -title~=^(wip|WIP).*
    actions:
      label:
        remove: ['in-progress :white_check_mark:']
