pull_request_rules:
  - name: Automatic merge when CI passes and 1 reviews (merge)
    conditions:
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
    actions:
      delete_head_branch: {}
      merge:
        method: merge
  
  - name: Automatic merge when will-merge status (merge)
    conditions:
      - '#changes-requested-reviews-by=0'
      - 'label=will-merge :+1:'
    actions:
      delete_head_branch: {}
      merge:
        method: merge
  
  # Labels
  - name: Auto add wip label
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ['in-progress :white_check_mark:']
  
  - name: Auto remove wip label
    conditions:
      - -title~=^(wip|WIP).*
    actions:
      label:
        remove: ['in-progress :white_check_mark:']